### ISSUE TITLE
Cannot find module '@color/colors/safe' from 'table-test.js'

### ISSUE THREAD

**Issue by speedytwenty** [cli-table/cli-table3#272]
The tests are presently failing with the error: `Cannot find module '@color/colors/safe' from 'table-test.js'`.

This bug should not affect production installations and is only induced when running this test.

This bug was introduced in #263 and not immediately noticed because of #271.
